name: wibsite
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  shared_preferences: ^2.0.6
  youtube_player_flutter: ^8.0.0
  provider: ^6.0.0
  url_launcher: ^6.0.20

  flutter_svg: ^1.1.0
  flutter:
    sdk: flutter
  dash_chat_2: ^0.0.18
  chat_gpt_sdk: ^2.2.8
  file_picker: ^5.0.0
  image_picker: ^0.8.7+4
  http: ^1.2.2
  google_fonts: ^6.2.1
  mongo_dart: ^0.10.3
  responsive_builder: ^0.7.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sign_in/
    - assets/
    - assets/sign_up/
    - assets/the_mainpage/
    - assets/meals/
    
