// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDnfBEZSyaQcjQUDSdHIho8kNxRvpCgg',
    appId: '1:296720097832:web:478d29129ef5acd2bccb1d',
    messagingSenderId: '296720097832',
    projectId: 'chatapp-59ea9',
    authDomain: 'chatapp-59ea9.firebaseapp.com',
    storageBucket: 'chatapp-59ea9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ehMGFmzZ69zg55Yo0PM1c1S26y1kW8Y',
    appId: '1:296720097832:android:3e093263671ea48dbccb1d',
    messagingSenderId: '296720097832',
    projectId: 'chatapp-59ea9',
    storageBucket: 'chatapp-59ea9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDnfBEZSyaQcjQUDSdHIho8kNxRvpCgg',
    appId: '1:296720097832:web:f9015cc3a5de6e25bccb1d',
    messagingSenderId: '296720097832',
    projectId: 'chatapp-59ea9',
    authDomain: 'chatapp-59ea9.firebaseapp.com',
    storageBucket: 'chatapp-59ea9.firebasestorage.app',
  );

}